### ISSUE TITLE
Meaning from Monitoring To-Do

### ISSUE THREAD

**Issue by amgottsegen** [amgottsegen/bay-area-monitoring#3]
### Meaning from Monitoring To-Do
- [ ] Make CSS styling more flexible (site looks funny on some screens)
- [x] Zoom buttons
- [ ] Guides (screenshots, video tutorials, explanation of where health hazard numbers come from and what they mean, etc.)
- [x] Fix js lock up
- [x] Follow up with Denny about data discrepancies with fenceline.org
- [x] Implement latest version of grapher
- [x] Change to 12-hour time on date axis
- [x] Show wind speed and direction on mouse hover over arrow
- [x] Margin at bottom of the data page with link to fenceline.org
- [ ] Display non-detects different than just a reading of 0 (possibly Schrodinger's cat approach-- shading between the detection limit and x axis to demonstrate that any value in that range is possible)
- [x] Fix bug reporting form (nginx prevents POST requests to static pages)
- [ ] Reformat landing page
- [ ] Add a Pittsburg tab
